name: bundle-extension

on:
  push:
    tags:
      - "v[1-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read


jobs:
  build:
    permissions:
      contents: write # for creating release
    name: Build packages 📦
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Clone repository ⬇️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Get release information 🛠
        id: release_info
        run: |
          echo "{VERSION}=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Print environment ℹ️
        run: |
          node --version
          npm --version
      - name: NPM setup
        run: npm ci
        working-directory: ./
      - name: Build 🏗
        run: npm run dist
      - name: Build Manifest v3 🏗
        run: npm run dist:mv3
      - name: Create release and upload artifact 🚀
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.release_info.outputs.VERSION }}"
          prerelease: false
          files: |
            dist/*.zip